/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    announcements: Announcement;
    events: Event;
    galleries: Gallery;
    programs: Program;
    staff: Staff;
    'pmb-registrations': PmbRegistration;
    messages: Message;
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    'pmb-registrations': PmbRegistrationsSelect<false> | PmbRegistrationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'campus-profile': CampusProfile;
    'pmb-info': PmbInfo;
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'campus-profile': CampusProfileSelect<false> | CampusProfileSelect<true>;
    'pmb-info': PmbInfoSelect<false> | PmbInfoSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  coverImage?: (number | null) | Media;
  /**
   * Ditampilkan di daftar berita (maks. 300 karakter).
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  category: 'akademik' | 'kemahasiswaan' | 'kegiatan' | 'prestasi' | 'umum';
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Gambar dan dokumen PDF yang dipakai di seluruh website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Gambarkan isi gambar secara singkat (untuk aksesibilitas & SEO). Untuk PDF, isi judul dokumen.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Berkas PDF atau gambar yang dapat diunduh pengunjung.
   */
  attachments?: (number | Media)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  pinned?: boolean | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  startDate: string;
  endDate?: string | null;
  location?: string | null;
  coverImage?: (number | null) | Media;
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Album dokumentasi foto & video kegiatan akademik dan kemahasiswaan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title: string;
  date?: string | null;
  coverImage?: (number | null) | Media;
  description?: string | null;
  photos?: (number | Media)[] | null;
  videos?:
    | {
        title?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Profil program studi (PAI, PGMI, PIAUD, HKI), tampil di /program-studi/{slug}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  name: string;
  /**
   * Contoh: PAI
   */
  code: string;
  degree: 'S1' | 'S2';
  department?: string | null;
  /**
   * Contoh: Baik Sekali (BAN-PT, 2025)
   */
  accreditation?: string | null;
  /**
   * Satu-dua kalimat untuk kartu program studi.
   */
  summary?: string | null;
  coverImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  vision?: string | null;
  missions?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  objectives?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  graduateProfiles?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  careers?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  curriculum?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  curriculumFile?: (number | null) | Media;
  head?: (number | null) | Staff;
  email?: string | null;
  /**
   * Contoh: https://jurnal.staimorowali.ac.id/index.php/nama-jurnal
   */
  journalUrl?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  order?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Direktori tenaga pendidik (dosen) dan tenaga kependidikan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  type: 'dosen' | 'tendik';
  photo?: (number | null) | Media;
  /**
   * Contoh: Ketua Program Studi PAI
   */
  position?: string | null;
  program?: (number | null) | Program;
  nidn?: string | null;
  academicRank?: ('tenaga-pengajar' | 'asisten-ahli' | 'lektor' | 'lektor-kepala' | 'profesor') | null;
  expertise?: string | null;
  education?: string | null;
  email?: string | null;
  sintaUrl?: string | null;
  scholarUrl?: string | null;
  active?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Data calon mahasiswa dari formulir pendaftaran awal di website. Gunakan tombol ekspor untuk mengunduh Excel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pmb-registrations".
 */
export interface PmbRegistration {
  id: number;
  registrationNumber?: string | null;
  status: 'baru' | 'diproses' | 'terverifikasi' | 'diterima' | 'batal';
  academicYear?: string | null;
  wave?: string | null;
  fullName: string;
  nik: string;
  gender: 'L' | 'P';
  birthPlace: string;
  birthDate: string;
  phone: string;
  email?: string | null;
  address: string;
  schoolOrigin: string;
  graduationYear: number;
  firstChoice: number | Program;
  secondChoice?: (number | null) | Program;
  consent?: boolean | null;
  /**
   * Tidak terlihat oleh pendaftar.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pesan dari formulir kontak website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  status: 'baru' | 'dibaca' | 'dibalas';
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  /**
   * Tidak terlihat oleh pengirim.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Halaman bebas yang disusun dari blok (page builder), tampil di /{slug}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout: (
    | HeroBlock
    | ContentBlock
    | MediaBlock
    | CallToActionBlock
    | CardGridBlock
    | StatsBlock
    | FaqBlock
    | VideoBlock
    | LatestPostsBlock
    | ProgramListBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  title: string;
  subtitle?: string | null;
  image?: (number | null) | Media;
  buttons?:
    | {
        label: string;
        /**
         * Tautan internal diawali "/", misalnya /berita. Tautan luar memakai https://
         */
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  image: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  title: string;
  text?: string | null;
  button?: {
    label?: string | null;
    /**
     * Tautan internal diawali "/", misalnya /berita. Tautan luar memakai https://
     */
    url?: string | null;
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  title?: string | null;
  intro?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  title?: string | null;
  items?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  title?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  title?: string | null;
  url: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostsBlock".
 */
export interface LatestPostsBlock {
  title?: string | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestPosts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramListBlock".
 */
export interface ProgramListBlock {
  title?: string | null;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'programList';
}
/**
 * Akun pengelola website. Admin mengelola semuanya; Editor mengelola konten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'pmb-registrations';
        value: number | PmbRegistration;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  coverImage?: T;
  excerpt?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  category?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  attachments?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  pinned?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  coverImage?: T;
  summary?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  coverImage?: T;
  description?: T;
  photos?: T;
  videos?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  degree?: T;
  department?: T;
  accreditation?: T;
  summary?: T;
  coverImage?: T;
  description?: T;
  vision?: T;
  missions?:
    | T
    | {
        text?: T;
        id?: T;
      };
  objectives?:
    | T
    | {
        text?: T;
        id?: T;
      };
  graduateProfiles?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  careers?:
    | T
    | {
        text?: T;
        id?: T;
      };
  curriculum?: T;
  curriculumFile?: T;
  head?: T;
  email?: T;
  journalUrl?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  order?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  photo?: T;
  position?: T;
  program?: T;
  nidn?: T;
  academicRank?: T;
  expertise?: T;
  education?: T;
  email?: T;
  sintaUrl?: T;
  scholarUrl?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pmb-registrations_select".
 */
export interface PmbRegistrationsSelect<T extends boolean = true> {
  registrationNumber?: T;
  status?: T;
  academicYear?: T;
  wave?: T;
  fullName?: T;
  nik?: T;
  gender?: T;
  birthPlace?: T;
  birthDate?: T;
  phone?: T;
  email?: T;
  address?: T;
  schoolOrigin?: T;
  graduationYear?: T;
  firstChoice?: T;
  secondChoice?: T;
  consent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        latestPosts?: T | LatestPostsBlockSelect<T>;
        programList?: T | ProgramListBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  image?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  button?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostsBlock_select".
 */
export interface LatestPostsBlockSelect<T extends boolean = true> {
  title?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramListBlock_select".
 */
export interface ProgramListBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Isi halaman beranda: banner, sorotan, statistik, dan bagian informasi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  slides?:
    | {
        title: string;
        subtitle?: string | null;
        image?: (number | null) | Media;
        primaryButton?: {
          label?: string | null;
          /**
           * Tautan internal diawali "/", misalnya /berita. Tautan luar memakai https://
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        secondaryButton?: {
          label?: string | null;
          /**
           * Tautan internal diawali "/", misalnya /berita. Tautan luar memakai https://
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        title: string;
        description?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        /**
         * Contoh: 4 atau 1.200+
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  newsLimit?: number | null;
  announcementLimit?: number | null;
  eventLimit?: number | null;
  journalCta?: {
    title?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Isi halaman /profil: sejarah, visi & misi, sambutan ketua, dan struktur organisasi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campus-profile".
 */
export interface CampusProfile {
  id: number;
  history?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  vision?: string | null;
  missions?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  goals?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  leaderName?: string | null;
  leaderTitle?: string | null;
  leaderPhoto?: (number | null) | Media;
  greeting?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  structureImage?: (number | null) | Media;
  officials?:
    | {
        position: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Isi halaman /pmb dan pengaturan formulir pendaftaran awal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pmb-info".
 */
export interface PmbInfo {
  id: number;
  isOpen?: boolean | null;
  /**
   * Contoh: 2027/2028
   */
  academicYear?: string | null;
  /**
   * Contoh: Gelombang I
   */
  wave?: string | null;
  closedMessage?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requirements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  schedule?:
    | {
        stage: string;
        /**
         * Contoh: 1–31 Maret 2027
         */
        date: string;
        id?: string | null;
      }[]
    | null;
  fees?:
    | {
        item: string;
        /**
         * Contoh: Rp250.000
         */
        amount: string;
        id?: string | null;
      }[]
    | null;
  guide?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  downloads?: (number | Media)[] | null;
  contacts?:
    | {
        name: string;
        /**
         * Contoh: 6281234567890
         */
        whatsapp: string;
        id?: string | null;
      }[]
    | null;
  successMessage?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Identitas kampus, kontak resmi, media sosial, dan tautan Rumah Jurnal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  fullName?: string | null;
  tagline?: string | null;
  /**
   * Disarankan PNG/SVG persegi beresolusi tinggi. Kosongkan untuk memakai logo bawaan.
   */
  logo?: (number | null) | Media;
  /**
   * Deskripsi bawaan untuk mesin pencari, maks. 160 karakter.
   */
  description?: string | null;
  address?: string | null;
  phone?: string | null;
  /**
   * Format internasional tanpa +, contoh: 6281234567890
   */
  whatsapp?: string | null;
  email?: string | null;
  /**
   * Contoh: Senin–Jumat, 08.00–16.00 WITA
   */
  officeHours?: string | null;
  /**
   * Google Maps > Bagikan > Sematkan peta, salin nilai src dari kode iframe.
   */
  mapEmbedUrl?: string | null;
  mapUrl?: string | null;
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'tiktok' | 'x' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  journalUrl: string;
  journalDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Menu utama di bagian atas website. Setiap menu dapat memiliki submenu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        /**
         * Tautan internal diawali "/", misalnya /berita. Tautan luar memakai https://
         */
        url: string;
        newTab?: boolean | null;
        children?:
          | {
              label: string;
              /**
               * Tautan internal diawali "/", misalnya /berita. Tautan luar memakai https://
               */
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    /**
     * Tautan internal diawali "/", misalnya /berita. Tautan luar memakai https://
     */
    url?: string | null;
    newTab?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Bagian bawah website: deskripsi singkat dan kolom tautan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  about?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Tautan internal diawali "/", misalnya /berita. Tautan luar memakai https://
               */
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * {tahun} otomatis diganti tahun berjalan.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
        primaryButton?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
            };
        secondaryButton?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        description?: T;
        url?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  newsLimit?: T;
  announcementLimit?: T;
  eventLimit?: T;
  journalCta?:
    | T
    | {
        title?: T;
        text?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campus-profile_select".
 */
export interface CampusProfileSelect<T extends boolean = true> {
  history?: T;
  vision?: T;
  missions?:
    | T
    | {
        text?: T;
        id?: T;
      };
  goals?:
    | T
    | {
        text?: T;
        id?: T;
      };
  leaderName?: T;
  leaderTitle?: T;
  leaderPhoto?: T;
  greeting?: T;
  structureImage?: T;
  officials?:
    | T
    | {
        position?: T;
        name?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pmb-info_select".
 */
export interface PmbInfoSelect<T extends boolean = true> {
  isOpen?: T;
  academicYear?: T;
  wave?: T;
  closedMessage?: T;
  intro?: T;
  requirements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  schedule?:
    | T
    | {
        stage?: T;
        date?: T;
        id?: T;
      };
  fees?:
    | T
    | {
        item?: T;
        amount?: T;
        id?: T;
      };
  guide?: T;
  downloads?: T;
  contacts?:
    | T
    | {
        name?: T;
        whatsapp?: T;
        id?: T;
      };
  successMessage?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  fullName?: T;
  tagline?: T;
  logo?: T;
  description?: T;
  address?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  officeHours?: T;
  mapEmbedUrl?: T;
  mapUrl?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  journalUrl?: T;
  journalDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  about?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}